[package]
name = "hex_colors"
version = "0.1.0"
authors = ["uselessgoddess <dodickgod@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1"
proc-macro2 = "1.0"
syn = { version = "1.0", features = ["extra-traits"] }
